In [ ]:
# EDA - Exploratory Data Analysis

In [ ]:
# Linear Regression
# Classification
# clustering

In [ ]:
import pandas as pd

data  = pd.read_csv('housing.csv');
data

Sq_Ft  Bedrooms  Bathrooms  Age          Price
0     3232         3          2   27  682777.150273
1     3107         4          3   14  712702.672025
2     2153         1          2   32  442952.288185
3     3764         3          3   22  766553.098528
4     1533         5          3   34  475021.303311
..     ...       ...        ...  ...            ...
995   2954         4          2   25  639568.713751
996   3225         3          2    3  676448.647926
997   1042         3          1   11  343628.053354
998   2299         2          2   35  482083.089811
999    739         3          3   25  311502.169738

[1000 rows x 5 columns]

In [ ]:
x = data.drop('Price',axis=1)
y = data['Price']
# x = data.iloc[:-1]

In [ ]:
x

Sq_Ft  Bedrooms  Bathrooms  Age
0     3232         3          2   27
1     3107         4          3   14
2     2153         1          2   32
3     3764         3          3   22
4     1533         5          3   34
..     ...       ...        ...  ...
995   2954         4          2   25
996   3225         3          2    3
997   1042         3          1   11
998   2299         2          2   35
999    739         3          3   25

[1000 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)

In [ ]:
x_train,x_test,y_train,y_test

(     Sq_Ft  Bedrooms  Bathrooms  Age
 29    1214         2          1   37
 535   2046         4          3   47
 695   1634         5          3    6
 557   4538         1          3   22
 836   3899         5          3   14
 ..     ...       ...        ...  ...
 106    594         3          3    6
 270   1441         1          3    6
 860   3562         2          1   45
 435   4547         2          3   41
 102   2992         1          1   23
 
 [800 rows x 4 columns],
      Sq_Ft  Bedrooms  Bathrooms  Age
 521   4104         3          3   13
 737   4557         3          3    4
 740   3768         1          2   39
 660    600         1          2   43
 411   3792         1          1   12
 ..     ...       ...        ...  ...
 408   4923         4          2   39
 332   3171         3          1   47
 208   3313         5          2   43
 613   2297         2          2   25
 78    2454         2          1   39
 
 [200 rows x 4 columns],
 29     307870.408170
 535    4989

In [ ]:
x_train,x_test

(     Sq_Ft  Bedrooms  Bathrooms  Age
 29    1214         2          1   37
 535   2046         4          3   47
 695   1634         5          3    6
 557   4538         1          3   22
 836   3899         5          3   14
 ..     ...       ...        ...  ...
 106    594         3          3    6
 270   1441         1          3    6
 860   3562         2          1   45
 435   4547         2          3   41
 102   2992         1          1   23
 
 [800 rows x 4 columns],
      Sq_Ft  Bedrooms  Bathrooms  Age
 521   4104         3          3   13
 737   4557         3          3    4
 740   3768         1          2   39
 660    600         1          2   43
 411   3792         1          1   12
 ..     ...       ...        ...  ...
 408   4923         4          2   39
 332   3171         3          1   47
 208   3313         5          2   43
 613   2297         2          2   25
 78    2454         2          1   39
 
 [200 rows x 4 columns])

In [ ]:
y_train,y_test

(29     307870.408170
 535    498942.223886
 695    523061.671937
 557    849567.829716
 836    843151.188664
            ...      
 106    313947.686042
 270    410657.886141
 860    683114.607132
 435    864233.537308
 102    547662.268868
 Name: Price, Length: 800, dtype: float64,
 521    852003.036410
 737    909967.708463
 740    696840.241979
 660    226663.057790
 411    704149.771929
            ...      
 408    934411.794123
 332    597631.590479
 208    691286.573230
 613    499218.352247
 78     497136.564735
 Name: Price, Length: 200, dtype: float64)

In [ ]:
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
# Make Predictions
y_pred = model.predict(x_test)
print(y_pred.size)
print(y_pred)

200
[ 837404.79362596  914371.73203535  696148.01790801  216431.49340931
  701236.16876095  954793.67063114  758179.63771807  523362.41042079
  765851.31985957  329381.56684768  531258.08698214  284912.01449287
  343362.46997166  653108.09472377  431972.72168823  247180.31038573
  351763.22856059  367192.4520705   885898.55734122  335203.9960503
  801504.13967384  794366.69649383  472153.44385792  562936.91310791
  799235.97665267  730209.54635917  414058.64507064 1000268.2385385
  615396.27008707  424901.53463127  375966.46247506  416677.35733242
  365223.09408231  721604.01404899  576882.90235026  521665.05606702
  652395.97090346  591396.69752773  861610.2956119   637303.90635985
  868007.16473625  893904.1147627   766142.28180096  469865.97267426
  568126.66199758  530011.06542851  257919.11937322  886718.48744034
  715801.55178069  935492.61578994  891778.39323548  712529.29437045
  724741.85268457  578881.06042935  351390.6355168   569401.11817172
  831383.53185259  622323.756205

In [ ]:
y_pred = model.predict([[5000,10,5,1]])
y_pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1173288.58953055])

In [ ]:
print('Actual Price :)',y_test)
print('Predicted Price :)',y_pred)

Actual Price :) 521    852003.036410
737    909967.708463
740    696840.241979
660    226663.057790
411    704149.771929
           ...      
408    934411.794123
332    597631.590479
208    691286.573230
613    499218.352247
78     497136.564735
Name: Price, Length: 200, dtype: float64
Predicted Price :) [1173288.58953055]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
data  = pd.read_csv('housing.csv');
data

X= data.iloc[: , :-1].values
print(X)

[[3232    3    2   27]
 [3107    4    3   14]
 [2153    1    2   32]
 ...
 [1042    3    1   11]
 [2299    2    2   35]
 [ 739    3    3   25]]


In [ ]:
from sklearn.model_selection import train_test_split    #the tool for split the data
from sklearn.linear_model import  LinearRegression

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size = 0.50)

NameError: name 'Y' is not defined